/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicSignInRouteImport } from './routes/_public/sign-in'
import { Route as AuthedOrgsIndexRouteImport } from './routes/_authed/orgs/index'
import { Route as PublicAuthCallbackRouteImport } from './routes/_public/auth.callback'
import { Route as AuthedOrgsNewRouteImport } from './routes/_authed/orgs/new'
import { Route as AuthedOrgsOrgIdRouteImport } from './routes/_authed/orgs/$orgId'
import { Route as AuthedOrgsOrgIdIndexRouteImport } from './routes/_authed/orgs/$orgId/index'
import { Route as AuthedOrgsOrgIdSummaryRouteImport } from './routes/_authed/orgs/$orgId/summary'
import { Route as AuthedOrgsOrgIdSettingsRouteImport } from './routes/_authed/orgs/$orgId/settings'
import { Route as AuthedOrgsOrgIdCategoriesRouteImport } from './routes/_authed/orgs/$orgId/categories'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicSignInRoute = PublicSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => PublicRoute,
} as any)
const AuthedOrgsIndexRoute = AuthedOrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => AuthedRoute,
} as any)
const PublicAuthCallbackRoute = PublicAuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => PublicRoute,
} as any)
const AuthedOrgsNewRoute = AuthedOrgsNewRouteImport.update({
  id: '/orgs/new',
  path: '/orgs/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrgsOrgIdRoute = AuthedOrgsOrgIdRouteImport.update({
  id: '/orgs/$orgId',
  path: '/orgs/$orgId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrgsOrgIdIndexRoute = AuthedOrgsOrgIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedOrgsOrgIdRoute,
} as any)
const AuthedOrgsOrgIdSummaryRoute = AuthedOrgsOrgIdSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => AuthedOrgsOrgIdRoute,
} as any)
const AuthedOrgsOrgIdSettingsRoute = AuthedOrgsOrgIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedOrgsOrgIdRoute,
} as any)
const AuthedOrgsOrgIdCategoriesRoute =
  AuthedOrgsOrgIdCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthedOrgsOrgIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof PublicSignInRoute
  '/orgs/$orgId': typeof AuthedOrgsOrgIdRouteWithChildren
  '/orgs/new': typeof AuthedOrgsNewRoute
  '/auth/callback': typeof PublicAuthCallbackRoute
  '/orgs/': typeof AuthedOrgsIndexRoute
  '/orgs/$orgId/categories': typeof AuthedOrgsOrgIdCategoriesRoute
  '/orgs/$orgId/settings': typeof AuthedOrgsOrgIdSettingsRoute
  '/orgs/$orgId/summary': typeof AuthedOrgsOrgIdSummaryRoute
  '/orgs/$orgId/': typeof AuthedOrgsOrgIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof PublicSignInRoute
  '/orgs/new': typeof AuthedOrgsNewRoute
  '/auth/callback': typeof PublicAuthCallbackRoute
  '/orgs': typeof AuthedOrgsIndexRoute
  '/orgs/$orgId/categories': typeof AuthedOrgsOrgIdCategoriesRoute
  '/orgs/$orgId/settings': typeof AuthedOrgsOrgIdSettingsRoute
  '/orgs/$orgId/summary': typeof AuthedOrgsOrgIdSummaryRoute
  '/orgs/$orgId': typeof AuthedOrgsOrgIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_public/sign-in': typeof PublicSignInRoute
  '/_authed/orgs/$orgId': typeof AuthedOrgsOrgIdRouteWithChildren
  '/_authed/orgs/new': typeof AuthedOrgsNewRoute
  '/_public/auth/callback': typeof PublicAuthCallbackRoute
  '/_authed/orgs/': typeof AuthedOrgsIndexRoute
  '/_authed/orgs/$orgId/categories': typeof AuthedOrgsOrgIdCategoriesRoute
  '/_authed/orgs/$orgId/settings': typeof AuthedOrgsOrgIdSettingsRoute
  '/_authed/orgs/$orgId/summary': typeof AuthedOrgsOrgIdSummaryRoute
  '/_authed/orgs/$orgId/': typeof AuthedOrgsOrgIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/orgs/$orgId'
    | '/orgs/new'
    | '/auth/callback'
    | '/orgs/'
    | '/orgs/$orgId/categories'
    | '/orgs/$orgId/settings'
    | '/orgs/$orgId/summary'
    | '/orgs/$orgId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/orgs/new'
    | '/auth/callback'
    | '/orgs'
    | '/orgs/$orgId/categories'
    | '/orgs/$orgId/settings'
    | '/orgs/$orgId/summary'
    | '/orgs/$orgId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_public'
    | '/_public/sign-in'
    | '/_authed/orgs/$orgId'
    | '/_authed/orgs/new'
    | '/_public/auth/callback'
    | '/_authed/orgs/'
    | '/_authed/orgs/$orgId/categories'
    | '/_authed/orgs/$orgId/settings'
    | '/_authed/orgs/$orgId/summary'
    | '/_authed/orgs/$orgId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/sign-in': {
      id: '/_public/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof PublicSignInRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authed/orgs/': {
      id: '/_authed/orgs/'
      path: '/orgs'
      fullPath: '/orgs/'
      preLoaderRoute: typeof AuthedOrgsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_public/auth/callback': {
      id: '/_public/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof PublicAuthCallbackRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authed/orgs/new': {
      id: '/_authed/orgs/new'
      path: '/orgs/new'
      fullPath: '/orgs/new'
      preLoaderRoute: typeof AuthedOrgsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/orgs/$orgId': {
      id: '/_authed/orgs/$orgId'
      path: '/orgs/$orgId'
      fullPath: '/orgs/$orgId'
      preLoaderRoute: typeof AuthedOrgsOrgIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/orgs/$orgId/': {
      id: '/_authed/orgs/$orgId/'
      path: '/'
      fullPath: '/orgs/$orgId/'
      preLoaderRoute: typeof AuthedOrgsOrgIdIndexRouteImport
      parentRoute: typeof AuthedOrgsOrgIdRoute
    }
    '/_authed/orgs/$orgId/summary': {
      id: '/_authed/orgs/$orgId/summary'
      path: '/summary'
      fullPath: '/orgs/$orgId/summary'
      preLoaderRoute: typeof AuthedOrgsOrgIdSummaryRouteImport
      parentRoute: typeof AuthedOrgsOrgIdRoute
    }
    '/_authed/orgs/$orgId/settings': {
      id: '/_authed/orgs/$orgId/settings'
      path: '/settings'
      fullPath: '/orgs/$orgId/settings'
      preLoaderRoute: typeof AuthedOrgsOrgIdSettingsRouteImport
      parentRoute: typeof AuthedOrgsOrgIdRoute
    }
    '/_authed/orgs/$orgId/categories': {
      id: '/_authed/orgs/$orgId/categories'
      path: '/categories'
      fullPath: '/orgs/$orgId/categories'
      preLoaderRoute: typeof AuthedOrgsOrgIdCategoriesRouteImport
      parentRoute: typeof AuthedOrgsOrgIdRoute
    }
  }
}

interface AuthedOrgsOrgIdRouteChildren {
  AuthedOrgsOrgIdCategoriesRoute: typeof AuthedOrgsOrgIdCategoriesRoute
  AuthedOrgsOrgIdSettingsRoute: typeof AuthedOrgsOrgIdSettingsRoute
  AuthedOrgsOrgIdSummaryRoute: typeof AuthedOrgsOrgIdSummaryRoute
  AuthedOrgsOrgIdIndexRoute: typeof AuthedOrgsOrgIdIndexRoute
}

const AuthedOrgsOrgIdRouteChildren: AuthedOrgsOrgIdRouteChildren = {
  AuthedOrgsOrgIdCategoriesRoute: AuthedOrgsOrgIdCategoriesRoute,
  AuthedOrgsOrgIdSettingsRoute: AuthedOrgsOrgIdSettingsRoute,
  AuthedOrgsOrgIdSummaryRoute: AuthedOrgsOrgIdSummaryRoute,
  AuthedOrgsOrgIdIndexRoute: AuthedOrgsOrgIdIndexRoute,
}

const AuthedOrgsOrgIdRouteWithChildren = AuthedOrgsOrgIdRoute._addFileChildren(
  AuthedOrgsOrgIdRouteChildren,
)

interface AuthedRouteChildren {
  AuthedOrgsOrgIdRoute: typeof AuthedOrgsOrgIdRouteWithChildren
  AuthedOrgsNewRoute: typeof AuthedOrgsNewRoute
  AuthedOrgsIndexRoute: typeof AuthedOrgsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedOrgsOrgIdRoute: AuthedOrgsOrgIdRouteWithChildren,
  AuthedOrgsNewRoute: AuthedOrgsNewRoute,
  AuthedOrgsIndexRoute: AuthedOrgsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface PublicRouteChildren {
  PublicSignInRoute: typeof PublicSignInRoute
  PublicAuthCallbackRoute: typeof PublicAuthCallbackRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicSignInRoute: PublicSignInRoute,
  PublicAuthCallbackRoute: PublicAuthCallbackRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
